### ISSUE TITLE
Slider component is not working on first attempt.

### ISSUE THREAD

**Issue by hotNipi** [Christian-Me/node-red-contrib-ui-iro-color-picker#1] opened 2021-05-15 05:02 UTC
Win 10
Desktop
Chrome  90.0.4430.212
Dashboard 2.28.2
iro-color-picker 0.0.3

Doing following and nothing more:

Drag node into workspace (connect to text node to see the output)
configure group, 
configure topic (side note: shouldn't be required parameter or if, then should fallback to default "topic") 

Add one component
configure component type to slider

Deploy.

What happens:
The slider moves on drag/click but on mouse release jumps back to initial position. Then on second drag/click it stays where it should but there is no output.  
(No errors in browser console/nr log)

Go back to component configuration
change the component to some other type
Deploy

Component works as expected

Go back to component configuration
Change component type to slider
Deploy

Component works as expected.

**Comment by Christian-Me** [comment] 2021-05-15 11:05
Hi,
thank you for your valuable feedback ... I can reproduce the issue.

It is caused by the default saturation is 0 = white in iro.js. if you have only the hue slider this cause the problem that the result is always white ...

Have to find a elegant way to avoid this without breaking other combinations. (have to cut the lawn before it starts raining ...)

If you add a saturation slider it should work.

Chris

**Comment by hotNipi** [comment] 2021-05-15 12:53
On more side note: 
For modal the content position calculations - with small screens it is possible that poitionLeft gets negative value. Should have guard like positionTop has.
` if (positionLeft<5) positionLeft = 5;`

**Comment by Christian-Me** [comment] 2021-05-15 13:56
Think I found a solution and many other bugs, included the guard, thank you.

The colour value defaulted to pure white. This don't exist in pure hue space (outer rim of the circle). I defaulted to RED {h:3060, s:100, v:100} which could be save for all (most) components

defaulted the topic type to msg, to msg.topic.

Still the iOS problems exists. I got the display OK but still all widgets below (after) the one triggering the modal catch all mouse events :(

Pushed version 0.0.4 to github if you like to give it a try (left many consol.logs in for now)

**Comment by hotNipi** [comment] 2021-05-15 15:00
I'm not on path to use the widget (no RGB lights to manipulate no other color related things in my setup)  but just helping out here to test cos I like it and I see high potential. So no need to rush with versions for me. :)

**Comment by hotNipi** [comment] 2021-05-15 15:31
Question: What is the idea behind the option show modal at the point of click?

**Comment by Christian-Me** [comment] 2021-05-15 16:12
Thank you for your help. I like to fix things ASAP otherwise they will never be done - and I like to have this thing away form my desk - it already took to much time.

I know you don't have safari devices - as the artless gauge has still issues on safari ;)  but this is perhaps related to the library itself,

I was only testing different options. Perhaps a setup where you have many buttons next to each other - to have a feedback which one you selected. I'm using many H801 (ESP8266 based 5ch pwm dimmers) and many DIY constant current dimmers for high power LEDs. So I have 5+ Values to set per device. Instead of using all my screen space I thought it would be perhaps nice to have 5 next to each other popping up with a big sliders on my phone - which does not work (currently) . But not tested it if it makes practical sense.

The developer of iro.js is planning to implement custom sliders - so perhaps usable for any kind of value input with a easy to use ui on small devices.

**Comment by hotNipi** [comment] 2021-05-15 16:31
Ok. It then makes sense when you have vertical sliders on modal and they appear near the button. For wider areas as the color wheel is, it just loses the connection I think. 
Anyway, I asked cos I didn't find that connection in my mind. 
I am on trying find out and provide another solution for positioning the modal content which may be a bit more reliable. The center of window option does not need any calculations and the group connected option works also. But for the click point I wasn't sure where to go.
Thing I see it missing right now is, that it needs to support at least the orientation change. It is possible to do for center window and the widget position but I cant see the solution for  the click point.

**Comment by Christian-Me** [comment] 2021-05-15 18:00
I made the background of the modal-content in transparent for debugging reason

Center Click (as expected)
![image](https://user-images.githubusercontent.com/15779507/118373514-9a760300-b5b7-11eb-81df-0e33fceb3dd2.png)
Center Window (as expected)
![image](https://user-images.githubusercontent.com/15779507/118373532-ba0d2b80-b5b7-11eb-9d23-dc2c674b3d4f.png)
Center Group (all fine)
![image](https://user-images.githubusercontent.com/15779507/118373540-c5605700-b5b7-11eb-9575-c461f1c170e2.png)

On iOS (safari) all works basically the same. Center Group is best for this purpose:

**Comment by hotNipi** [comment] 2021-05-15 18:17
Yeah, it works. I was just on push it a bit to support the orientation change cos that may happen depending on how the user creates the dashboard layout. Some of them use layouts for tabs where it forces to use different orientation on small screens. And if then opened modal is in the view, it fails to hold the position. Nothing major. I saw the way but then the click point took it down.

**Comment by Christian-Me** [comment] 2021-05-15 19:13
Happy for all input! The click point is not a must, I was just experimenting.

**Comment by hotNipi** [comment] 2021-05-15 19:24
The idea is to use flex for the modal as for container and for modal content margin auto holds it in center. Then if option is to hold it in the widget group, the group position can be retrieved via 
` var widgetPos = document.getElementById("iro-color-container-${config.id}").getBoundingClientRect();` 
and position calculation is pretty same as it is now but bases on that measured widget area
  ` positionTop = widgetPos.y + widgetPos.height/2- ${config.widgetHeightPx/2}` 
and the position change is done via 
`modalContent.style.marginLeft = positionLeft + "px";`

That way the center of page  position does not require any calculations and it works straight for orientation also, but recalculation needs to be added for the group based option.

**Comment by Christian-Me** [comment] 2021-05-17 22:47
Thank you this - will test it ASAP.  Happy to learn more in modern web development. My last experiences are more than 20 years old - long before reactive web design.

**Comment by Christian-Me** [comment] 2021-06-03 23:10
Hi ... finally version 0.1.0 is on my repo ... thank you for your suggestions and insights! Helped a lot. The initial size calculation code is a mess but works ...

**Comment by Christian-Me** [comment] 2021-07-30 21:50
Think we can close this? Or did you found any unfixed issues?

**Closed** 2022-01-12 19:24 UTC
Labels: bug, fixed - testing
